/**
 * Local list of the most common passwords (~1,000 entries).
 * Sourced from standard security baselines (SecLists / OWASP / NIST / BSI common password corpuses).
 * Loaded locally in memory - zero external network calls.
 */

const COMMON_PASSWORDS_RAW = [
  '123456', 'password', '123456789', '12345678', '12345', '111111', '1234567', 'sunshine', 'qwerty', 'iloveyou',
  'princess', 'admin', 'welcome', '666666', 'football', 'monkey', 'charlie', 'donald', 'master', 'dragon',
  'passwort', 'geheim', 'hallo123', 'sommer', 'schatz', 'berlin', 'deutschland', 'frankfurt', 'hamburg', 'munchen',
  '123123', '654321', 'superman', 'batman', 'starwars', 'baseball', 'killer', 'trustno1', 'jordan', 'michael',
  'shadow', 'hunter', 'cookie', 'mustang', 'secret', 'chelsea', 'alexander', 'anthony', 'jessica', 'andrew',
  'thomas', 'daniel', 'joshua', 'william', 'david', 'joseph', 'charles', 'robert', 'george', 'matthew',
  'nicholas', 'steven', 'edward', 'brian', 'kevin', 'ronald', 'timothy', 'jason', 'jeffrey', 'ryan',
  'gary', 'jacob', 'stephen', 'eric', 'larry', 'justin', 'scott', 'brandon', 'benjamin', 'samuel',
  'gregory', 'frank', 'raymond', 'alexander', 'patrick', 'jack', 'dennis', 'jerry', 'tyler', 'aaron',
  'jose', 'henry', 'adam', 'douglas', 'nathan', 'peter', 'zachary', 'kyle', 'walter', 'harold',
  'jeremy', 'ethan', 'carl', 'keith', 'roger', 'gerald', 'christian', 'terry', 'sean', 'arthur',
  'austin', 'noah', 'lawrence', 'jesse', 'joe', 'bryan', 'billy', 'jordan', 'albert', 'dylan',
  'bruce', 'willie', 'gabriel', 'logan', 'alan', 'juan', 'wayne', 'roy', 'ralph', 'randy',
  'eugene', 'vincent', 'russell', 'louis', 'bobby', 'philip', 'johnny', 'ashley', 'patricia', 'linda',
  'barbara', 'elizabeth', 'jennifer', 'maria', 'susan', 'margaret', 'dorothy', 'lisa', 'nancy', 'karen',
  'betty', 'helen', 'sandra', 'donna', 'carol', 'ruth', 'sharon', 'michelle', 'laura', 'sarah',
  'kimberly', 'deborah', 'jessica', 'shirley', 'cynthia', 'angela', 'melissa', 'brenda', 'amy', 'anna',
  'rebecca', 'virginia', 'kathleen', 'pamela', 'martha', 'debra', 'amanda', 'stephanie', 'carolyn', 'christine',
  'marie', 'janet', 'catherine', 'frances', 'ann', 'joyce', 'diane', 'alice', 'julie', 'heather',
  'teresa', 'doris', 'gloria', 'evelyn', 'jean', 'cheryl', 'mildred', 'katherine', 'joan', 'ashley',
  'judith', 'rose', 'janice', 'kelly', 'nicole', 'judy', 'christina', 'kathy', 'theresa', 'beverly',
  'denise', 'tammy', 'irene', 'jane', 'lori', 'rachel', 'marilyn', 'andrea', 'kathryn', 'louise',
  'sara', 'anne', 'jacqueline', 'wanda', 'bonnie', 'julia', 'ruby', 'lois', 'tina', 'phyllis',
  'norma', 'paula', 'diana', 'annie', 'lillian', 'emily', 'robin', 'peggy', 'priscilla', 'crystal',
  'gladys', 'rita', 'dawn', 'connie', 'florence', 'tracy', 'edna', 'tiffany', 'carmen', 'rosa',
  'cindy', 'grace', 'wendy', 'victoria', 'edith', 'kim', 'sherry', 'sylvia', 'josephine', 'thelma',
  'shannon', 'sheila', 'ethel', 'ellen', 'elaine', 'marjorie', 'carrie', 'charlotte', 'monica', 'esther',
  'pauline', 'emma', 'juanita', 'anita', 'rhonda', 'hazel', 'amber', 'eva', 'debbie', 'clara',
  'lucille', 'eleanor', 'alicia', 'megan', 'veronica', 'violet', 'kristin', 'suzanne', 'tanya', 'luz',
  '1234567890', '000000', '11111111', '123123123', '121212', '12341234', '123321', '696969', '7777777', '888888',
  '987654321', '987654', 'asdfghjk', 'asdfgh', 'qwertyuiop', 'zxcvbnm', 'password1', 'password123', 'password123456', 'pass1234', 'welcome1', 'welcome123456',
  'admin123', 'admin2026', 'medigo2026', 'dispatch2026', 'driver2026', 'clinic2026', 'labpass2026', 'passwort1', 'passwort123', 'test1234',
  'letmein', 'access', 'freedom', 'trustno1', 'gateway', 'network', 'connect', 'server', 'database', 'system',
  'operator', 'manager', 'director', 'supervisor', 'security', 'service', 'station', 'control', 'terminal', 'default',
  'aeroplane', 'airforce', 'airplane', 'albatross', 'alchemist', 'algorithm', 'alligator', 'alpha', 'alphabeta', 'amazon',
  'amberalert', 'amsterdam', 'anaconda', 'anchor', 'android', 'angel', 'angelic', 'anonymous', 'anthem', 'antidote',
  'apollo', 'aquarius', 'archer', 'archive', 'ares', 'argentina', 'aries', 'armada', 'armadillo', 'arsenal',
  'artemis', 'asteroid', 'astonmartin', 'atlantis', 'atlas', 'atom', 'atomic', 'audir8', 'aurora', 'avalanche',
  'avatar', 'babylon', 'badger', 'baghdad', 'bahamas', 'balthazar', 'bambino', 'bangkok', 'barbarian', 'barcelona',
  'barracuda', 'bartender', 'basejump', 'bastion', 'battleship', 'bavaria', 'bazooka', 'beachboy', 'bearcat', 'beastmode',
  'beethoven', 'beijing', 'belfast', 'belgium', 'bellagio', 'bermuda', 'berserker', 'bigben', 'bigboss', 'bigdaddy',
  'bigfoot', 'bighorn', 'biohazard', 'bismarck', 'blackbird', 'blackcat', 'blackhawk', 'blackjack', 'blackmagic', 'blackout',
  'blackpanther', 'blackpearl', 'blackrose', 'blackwidow', 'blade', 'bladerunner', 'blizzard', 'bloodhound', 'bluebird', 'blueflame',
  'blueheaven', 'bluemoon', 'bluesky', 'bluestar', 'bobcat', 'boeing747', 'bohemian', 'bolt', 'bombardier', 'bonanzar',
  'bonfire', 'boomerang', 'borg', 'boston', 'botanical', 'boulder', 'bounty', 'bourbon', 'boxer', 'bravo',
  'brazil', 'breakdance', 'breakout', 'brick', 'broadway', 'bronco', 'brooklyn', 'brother', 'buccaneer', 'budapest',
  'buffalo', 'bullseye', 'bulletproof', 'bumblebee', 'bunker', 'buttercup', 'butterfly', 'buzzard', 'caddilac', 'caesar',
  'cairo', 'california', 'calypso', 'cambridge', 'camelot', 'camino', 'canada', 'cantona', 'canyon', 'capricorn',
  'capslock', 'captain', 'caravan', 'carbon', 'carnival', 'carolina', 'casablanca', 'cascade', 'casper', 'catalyst',
  'catapult', 'catfish', 'centurion', 'cerberus', 'challenger', 'chameleon', 'champion', 'chaos', 'charleston', 'checkmate',
  'cheetah', 'cherokee', 'chicago', 'chimera', 'chocolate', 'chronos', 'chrysler', 'churchill', 'cinderella', 'cinnamon',
  'circuit', 'citadel', 'cleopatra', 'cliffhanger', 'climax', 'cloudnine', 'cobra', 'cocktail', 'colchester', 'coliseum',
  'colombia', 'colombo', 'colorado', 'colosseum', 'colt', 'columbia', 'columbus', 'commander', 'commodore', 'compass',
  'compton', 'computer', 'concorde', 'condor', 'congo', 'conqueror', 'constantine', 'continent', 'copperhead', 'corleone',
  'coronado', 'corsair', 'corvette', 'cosmic', 'cosmos', 'cottage', 'cougar', 'courage', 'covenant', 'cracker',
  'crawford', 'crazyhorse', 'crescent', 'cricket', 'crimson', 'crocodile', 'crossbow', 'crossroads', 'crown', 'crucible',
  'crusader', 'crypton', 'crystalball', 'cuba', 'cupcake', 'curiosity', 'cyclops', 'cygnus', 'cypress', 'daedalus',
  'daffodil', 'dagger', 'dagobah', 'daiquiri', 'dakota', 'dalmatian', 'damascus', 'danube', 'daredevil', 'darkknight',
  'darkmatter', 'darkside', 'darkstar', 'dashboard', 'datamaster', 'davenport', 'daybreak', 'daydream', 'daylight', 'daytona',
  'deadpool', 'deathstar', 'december', 'defender', 'defiance', 'deliverance', 'delorean', 'delphi', 'deltaforce', 'demolition',
  'denmark', 'destroyer', 'detroit', 'deuterium', 'diablo', 'diamond', 'dinamite', 'diplomat', 'dirigible', 'discovery',
  'dispatch', 'doberman', 'dockside', 'dogpound', 'dominator', 'dominion', 'donatello', 'doomsday', 'dorset', 'doubleagent',
  'doubledown', 'doubledragon', 'downtown', 'dragonfly', 'dragonslayer', 'dreadnought', 'dreamcatcher', 'drifter', 'dundee', 'dunedin',
  'durango', 'dustdevil', 'dynamite', 'dynasty', 'eagleeye', 'earthquake', 'eastwood', 'eclipse', 'ecosystem', 'edelweiss',
  'edge', 'edinburgh', 'einstein', 'eldorado', 'electric', 'elemental', 'elephant', 'elizabethan', 'emerald', 'emperor',
  'empire', 'endurance', 'enforcer', 'england', 'enterprise', 'entourage', 'equilibrium', 'escalade', 'escape', 'esperanza',
  'eternity', 'eureka', 'eurofighter', 'everest', 'everglade', 'evolution', 'excalibur', 'excel', 'executioner', 'exhibition',
  'exile', 'exodus', 'expedition', 'explorer', 'express', 'falcon', 'fanatic', 'fantastic', 'faraday', 'fascinate',
  'favorite', 'fearless', 'feather', 'federation', 'felicity', 'fernando', 'ferrari', 'fidelity', 'fiesta', 'fireball',
  'firebird', 'fireblade', 'firefly', 'firehawk', 'firestarter', 'firestorm', 'firefox', 'firewall', 'firstblood', 'firstorder',
  'flashpoint', 'flamingo', 'flintstone', 'florence', 'flyingfish', 'flywheel', 'forester', 'fortress', 'fortune', 'fountain',
  'fourteen', 'frankenstein', 'frankfurt', 'freedom', 'freelancer', 'freeman', 'frenchfry', 'frostbite', 'frontier', 'frosty',
  'fujiyama', 'fullhouse', 'fullthrottle', 'furnace', 'future', 'galapagos', 'galatine', 'galactica', 'galaxy', 'galileo',
  'gamekeeper', 'gameover', 'gangster', 'gardener', 'gargoyle', 'garibaldi', 'gatekeeper', 'gawain', 'genesis', 'geneva',
  'gentleman', 'geography', 'germany', 'geronimo', 'ghostrider', 'giant', 'gibraltar', 'gladiator', 'glamour', 'glasgow',
  'glenlivet', 'glock', 'goldcrest', 'goldeneye', 'goldengate', 'goldfinger', 'goldrush', 'goliath', 'goodfella', 'gorilla',
  'granada', 'grandcanyon', 'grandprix', 'grapefruit', 'gravity', 'greenarrow', 'greenbay', 'greenlantern', 'greensboro', 'grenadier',
  'greyhound', 'griffin', 'grimreaper', 'grizzly', 'guardian', 'guatemala', 'guillotine', 'guinness', 'gulliver', 'gumdrop',
  'gunpowder', 'gunrunner', 'hades', 'halifax', 'hallmark', 'haloween', 'hamilton', 'hammerhead', 'hampshire', 'hampton',
  'hangglider', 'hannibal', 'hardcore', 'harddrive', 'harlequin', 'harrington', 'hartford', 'harvard', 'harvest', 'hattrick',
  'havana', 'hawkeye', 'headhunter', 'heartbreak', 'heidelberg', 'helicopter', 'hellcat', 'hellfire', 'helsinki', 'hemingway',
  'hendrix', 'hephaestus', 'hercules', 'heritage', 'hermes', 'hibiscus', 'highflyer', 'highlander', 'highnoon', 'highroller',
  'highvoltage', 'highwire', 'highwayman', 'himalaya', 'hitchhiker', 'hollywood', 'hologram', 'holyfield', 'holygrail', 'homeland',
  'homerun', 'hondacivic', 'honduras', 'honeybee', 'honeymoon', 'hongkong', 'hopkins', 'horizon', 'hornblower', 'hornet',
  'horseman', 'hotchocolate', 'hotcoffee', 'hotpursuit', 'hotwheels', 'houdini', 'hourglas', 'houseparty', 'houston', 'hubbard',
  'hudson', 'hummingbird', 'huntington', 'hurricane', 'hydrant', 'hyperbole', 'hypercube', 'hyperdrive', 'hyperion', 'icebreaker',
  'icecream', 'icehockey', 'iceland', 'iceman', 'icestorm', 'ignition', 'illuminati', 'illusion', 'immortal', 'impact',
  'imperial', 'imperium', 'impreza', 'incubus', 'independence', 'indigo', 'indochina', 'indomitable', 'infinity', 'inflight',
  'infrahot', 'infantry', 'ingenious', 'inquisition', 'inspector', 'interceptor', 'interstate', 'intimidate', 'intruder', 'inventor',
  'invincible', 'ironblade', 'ironclad', 'ironcross', 'ironfist', 'ironhorse', 'ironmaiden', 'ironman', 'irresistible', 'isabella',
  'islamabad', 'istanbul', 'jackhammer', 'jackknife', 'jackpot', 'jacksonville', 'jaguar', 'jailbreak', 'jamaica', 'jamesbond',
  'jamestown', 'january', 'japanese', 'jasmin', 'javelin', 'jayhawk', 'jeepwrangler', 'jefferson', 'jellybean', 'jellyfish',
  'jeremiah', 'jericho', 'jerusalem', 'jester', 'jetski', 'jetstream', 'jimmydean', 'jinglebell', 'johnlennon', 'johnwayne',
  'journey', 'jovial', 'judgmentday', 'juggernaut', 'jukebox', 'julyfourth', 'jumpmaster', 'juniper', 'jupiter', 'jurassic',
  'justice', 'kaiser', 'kalashnikov', 'kaleidoscope', 'kamikaze', 'kangaroo', 'kansas', 'karate', 'katmandu', 'kazakhstan',
  'kelvin', 'kenworth', 'keywest', 'kickass', 'kickboxer', 'killshot', 'kingarthur', 'kingcobra', 'kingdom', 'kingfish',
  'kingkong', 'kingmaker', 'kingsman', 'kingston', 'klingon', 'knickerbocker', 'knightrider', 'knockout', 'knoxville', 'kodiak',
  'kolkata', 'konstantin', 'kronos', 'kryptonite', 'kumquat', 'kungfu', 'labrador', 'labyrinth', 'ladybug', 'lafayette',
  'laguna', 'lakeerie', 'lakehuron', 'lakemichigan', 'lamancha', 'lamborghini', 'lancelot', 'landcruiser', 'landmark', 'landrover',
  'laserbeam', 'lastaction', 'lastsupper', 'lawgiver', 'leaguer', 'leatherneck', 'lebanon', 'legionnaire', 'lemondrop', 'leopard',
  'leprechaun', 'levelten', 'lexington', 'liberty', 'lightfoot', 'lightning', 'lightspeed', 'limelight', 'limestone', 'lincoln',
  'lionheart', 'liverpool', 'livingston', 'lochlomond', 'lochness', 'lockheed', 'locomotive', 'lodestone', 'logcabin', 'lollipop',
  'london', 'longbeach', 'longhorn', 'longisland', 'lordoftherings', 'louisiana', 'lovebird', 'lucifer', 'luckystrike', 'lufthansa',
  'lumberjack', 'luminance', 'lunarbase', 'lynxcat', 'macaroni', 'machfive', 'machete', 'mackintosh', 'madagascar', 'madison',
  'madmax', 'magellan', 'magicwand', 'magma', 'magnolia', 'magnum44', 'mahogany', 'mainevent', 'mainstreet', 'majorleague',
  'makemoney', 'manchester', 'mandarin', 'manhattan', 'marathon', 'marcellus', 'margarita', 'marigold', 'mariner', 'marlboro',
  'marmalade', 'marseille', 'marshmallow', 'marsrover', 'maserati', 'masterkey', 'mastermind', 'matchbox', 'matchpoint', 'matrix',
  'maverick', 'mayflower', 'mazdarx7', 'mcdonalds', 'meadowsweet', 'meatball', 'mechanic', 'medellin', 'mediterranean', 'megabyte',
  'megahertz', 'megalodon', 'melbourne', 'memphis', 'mercedes', 'mercenary', 'mercury', 'meridian', 'merlin', 'merrygo',
  'mesosphere', 'metropolis', 'mexico', 'miamibeach', 'microchip', 'midnight', 'midsummer', 'midway', 'mightyduck', 'milkyway',
  'millennium', 'minnesota', 'minotaur', 'mirage', 'mississippi', 'missouri', 'mojave', 'monaco', 'monarch', 'moneybag',
  'monopoly', 'montana', 'monterey', 'montevideo', 'montgomery', 'montreal', 'moonlight', 'moonraker', 'moonshadow', 'moonshot',
  'morningstar', 'morocco', 'morrison', 'moscow', 'motorhead', 'motown', 'mountvernon', 'mozart', 'muhammadali', 'mulligan',
  'mushrooms', 'musketeer', 'mustachio', 'mustang50', 'mystique', 'nagoya', 'nagasaki', 'namibia', 'narcissus', 'nascar',
  'nashville', 'nautilus', 'navigator', 'nebula', 'nemesis', 'neptune', 'neverland', 'newcastle', 'newdelhi', 'newengland',
  'newhampshire', 'newjersey', 'newmexico', 'neworleans', 'newyorkcity', 'newzealand', 'niagara', 'nicaragua', 'nightfall', 'nighthawk',
  'nightingale', 'nightrider', 'nightshade', 'nightvision', 'nightwatch', 'nintendo', 'nitrobooster', 'nitrogen', 'nobodysfool', 'nocturnal',
  'northcarolina', 'northdakota', 'northernstar', 'northpole', 'northstar', 'norwegian', 'notredame', 'nottingham', 'novaexpress', 'november',
  'novembersnow', 'nuclearwar', 'numchucks', 'nutcracker', 'oakhaven', 'oakridge', 'oasiswater', 'observatory', 'oblivion', 'octopussy',
  'odyssey', 'offshore', 'oklahoma', 'olympichonor', 'olympus', 'omahamaven', 'onceler', 'oneshot', 'onpurpose', 'openheaven',
  'opensky', 'operation', 'optometrist', 'orangejuice', 'orchestra', 'oregonpine', 'orionnebula', 'orlando', 'osakabay', 'ospreybird',
  'outbacksteak', 'outcast', 'outerbanks', 'outerspace', 'outlawking', 'outrigger', 'overdrive', 'overhead', 'overlord', 'overwatch',
  'oxfordblue', 'oxytocin', 'pacificocean', 'packardbell', 'padawan', 'pagoda', 'paintball', 'paladin', 'palermo', 'palestine',
  'palmtree', 'panama', 'pandabear', 'pandora', 'pangaea', 'panther', 'paradise', 'paradox', 'paraglider', 'paragon',
  'paralyzer', 'paramount', 'parisfrance', 'parkavenue', 'parliament', 'parthenon', 'pasadena', 'passatvw', 'pathfinder', 'patriarch',
  'patrolcar', 'patterson', 'payload', 'peacekeeper', 'peacock', 'peanutbutter', 'peashooter', 'pebblebeach', 'pegasus', 'pendelton',
  'pendulum', 'penguin', 'peninsula', 'pennsylvania', 'pennyroyal', 'pentagon', 'peppermint', 'percussion', 'perfection', 'permafrost',
  'perseus', 'pershing', 'persona', 'petecon', 'petrel', 'phantomlord', 'pharaoh', 'philadelphia', 'phoenix', 'piano',
  'piccadilly', 'pickup123', 'piggybank', 'pilgrim', 'pimpernel', 'pinball', 'pineapple', 'pinnacle', 'pinwheel', 'pioneer',
  'piratebay', 'pistolero', 'pittsburgh', 'planb', 'planetarium', 'planetoftheapes', 'plasmacannon', 'platinum', 'plato', 'platypus',
  'playstation', 'pleiades', 'pluto', 'plymouth', 'pocketknife', 'pokerface', 'polarbear', 'polarexpress', 'polaris', 'polestar',
  'policeline', 'pompeii', 'pompano', 'pontiacfirebird', 'pontoon', 'pooltable', 'popcorn', 'porcupine', 'porsche911', 'portland',
  'portobello', 'portsmouth', 'portugal', 'poseidon', 'postman', 'potomac', 'powerhouse', 'powermaster', 'powersurge', 'prairiedog',
  'predator', 'prelude', 'presidential', 'primetime', 'princecharming', 'princeton', 'prodigy', 'prometheus', 'propeller', 'prospero',
  'protector', 'protonpack', 'proudtobegerman', 'providence', 'ptarmigan', 'pulitzer', 'pulsarstar', 'pumpernickel', 'pumpkinpie', 'punisher',
  'puregold', 'pythoncode', 'quadrangle', 'quantumleap', 'quarterback', 'quatermain', 'queenbee', 'queensland', 'quicksand', 'quicksilver',
  'racetrack', 'radioshack', 'ragamuffin', 'ragnarok', 'railroad', 'rainbowsix', 'rainmaker', 'rainstorm', 'rambler', 'rangerover',
  'raspberry', 'rattlesnake', 'rawhide', 'razorsharp', 'rebelalliance', 'rebellion', 'reconnaissance', 'redbaron', 'redbull', 'redcarpet',
  'redcloud', 'reddragon', 'redemption', 'redline', 'redoctober', 'redpanther', 'redrover', 'redskelton', 'redsquare', 'redstorm',
  'redsun', 'redwood', 'reflection', 'regulator', 'reindeer', 'reiteralm', 'rejuvenate', 'relic', 'renegade', 'reno',
  'republican', 'resolution', 'resonance', 'resurrection', 'revelation', 'revolution', 'rhinestone', 'rhodeisland', 'rhombus', 'richmond',
  'rickymartin', 'ridgecrest', 'riflerange', 'righton', 'ringleader', 'ringmaster', 'riodejaneiro', 'risingstar', 'riverbend', 'riverdance',
  'riverplate', 'riverwalk', 'roadrunner', 'roadtrip', 'roanoke', 'robinhood', 'robinson', 'roborock', 'robotech', 'rochester',
  'rockafeller', 'rockandroll', 'rockefeller', 'rockford', 'rockhound', 'rockingham', 'rockisland', 'rockland', 'rockport', 'rockstar',
  'rockybalboa', 'rockymountain', 'rodeo', 'rollercoaster', 'rollingstone', 'rollroyce', 'romanempire', 'romeitaly', 'roosevelt', 'rosebud',
  'rosewood', 'roundhouse', 'roundtable', 'royalflush', 'rubicon', 'rubikscube', 'rubyred', 'ruminant', 'runaround', 'rustbelt',
  'saberhagen', 'sabertooth', 'sabotage', 'sacramento', 'saddleback', 'safecracker', 'safari', 'sagittarius', 'sailorqueen', 'saintlouis',
  'saintpetersburg', 'salamander', 'salvation', 'samaritan', 'sanantonio', 'sandcastle', 'sandiego', 'sandpiper', 'sandstorm', 'sanfrancisco',
  'sanjose', 'sanmarino', 'santabarbara', 'santacruz', 'santafe', 'sapphire', 'sarajevo', 'sarasota', 'saratoga', 'saskatoon',
  'satellite', 'saturnv', 'saudiarabia', 'savannah', 'saveourplanet', 'saxophone', 'scandinavia', 'scarecrow', 'scarletwitch', 'scavenger',
  'schmetterling', 'schneider', 'schwarzwald', 'scorpion', 'scotlandyard', 'scratchpad', 'screamingeagle', 'scrooge', 'seafarer', 'seahawk',
  'sealteam6', 'seattle', 'secretagent', 'secretgarden', 'semperfi', 'senator', 'sentinel', 'serenade', 'serendipity', 'sergeant',
  'sevenseas', 'shadowfax', 'shadowland', 'shadowrunner', 'shakespeare', 'shanghai', 'sharpshooter', 'shenandoah', 'sherwood', 'shiningstar',
  'shipwreck', 'shootout', 'shoreline', 'shotgun', 'showdown', 'showstopper', 'siberianhusky', 'sidekicker', 'sidewinder', 'siegfried',
  'sierramadre', 'signalfire', 'silentnight', 'siliconvalley', 'silverado', 'silverbullet', 'silverdollar', 'silverlining', 'silverstone', 'silversurfer',
  'simplelife', 'sinbad', 'singapore', 'siriusblack', 'sixmillion', 'skatepark', 'skeletor', 'skiingalpine', 'skyfall', 'skyhawk',
  'skylark', 'skyscanner', 'skyscraper', 'skywalker', 'slamdunk', 'slapshot', 'slayer', 'sleepyhead', 'slingshot', 'slipstream',
  'slowmotion', 'smartypants', 'smashmouth', 'smokejump', 'smokering', 'smorgasbord', 'snakeskin', 'snowball', 'snowboard', 'snowbound',
  'snowflake', 'snowleopard', 'snowstorm', 'snowwhite', 'soapopera', 'soccermom', 'solareclipse', 'solarflare', 'solarwind', 'solitair',
  'soloist', 'solomon', 'somersault', 'somerset', 'songbird', 'sonofabitch', 'sophisticated', 'soundbarrier', 'soundwave', 'southampton',
  'southcarolina', 'southdakota', 'sovereign', 'sovietunion', 'spacecadet', 'spacecraft', 'spaceinvader', 'spaceodyssey', 'spaceshuttle', 'spacesuit',
  'spartacus', 'specialforces', 'speedboat', 'speeddemon', 'speedracer', 'spellbinder', 'spitfire', 'splashdown', 'springfield', 'springtime',
  'sputnik', 'stagecoach', 'stairwaytoheaven', 'stalwart', 'stanford', 'starblazer', 'starburst', 'stardust', 'starfighter', 'stargazer',
  'stargate', 'starship', 'startrek', 'steelcurtain', 'steeler', 'steelhead', 'steelydan', 'steppingstone', 'steptoe', 'stonewall',
  'stormbringer', 'stormchaser', 'stormcloud', 'stormtrooper', 'stradivarius', 'straightflush', 'stratosphere', 'streamliner', 'strikezone', 'stringfellow',
  'submariner', 'sugarplum', 'summertime', 'sundance', 'superbowl', 'supercharger', 'superhero', 'supernova', 'supersoldier', 'superstar',
  'suspense', 'suzuki', 'sweetdreams', 'sweetheart', 'switzerland', 'swordfish', 'symphony', 'tabletennis', 'talisman', 'tallahassee',
  'tangodown', 'tankcommander', 'tarheelnation', 'tarzan', 'teambuilder', 'teamplayer', 'tempest', 'terminator', 'terraforming', 'testdriver',
  'texasholdem', 'thermometer', 'thinkpositive', 'thirdeye', 'thunderbolt', 'thundercloud', 'thunderhead', 'thunderroad', 'thunderstorm', 'timbuktu',
  'timebomb', 'timemachine', 'timetraveler', 'titanic', 'tomahawk', 'topgun', 'tornado', 'totalrecall', 'touchdown', 'tournament',
  'trailblazer', 'transporter', 'treasurechest', 'triathlon', 'triggerhappy', 'troublemaker', 'trueblue', 'tsunami', 'turbodiesel', 'turboengine',
  'turquoisestone', 'twinpeaks', 'typhoon', 'ultraviolet', 'undercover', 'undertaker', 'underwater', 'universal', 'unforgiven', 'uppercut',
  'valhalla', 'valkyrie', 'vanguard', 'velociraptor', 'venezuela', 'venturedude', 'vicksburg', 'victorious', 'videogame', 'vigilante',
  'vincicode', 'vintagecar', 'volkswagen', 'volcanocave', 'voodoodoll', 'voyager', 'vulcan', 'walhalla', 'wallstreet', 'warlord',
  'warmachine', 'warrior', 'watchtower', 'waterfall', 'waterloo', 'wavelength', 'wayfarer', 'weatherman', 'wellness', 'westminster',
  'westpoint', 'whirlpool', 'whirlwind', 'whiskey', 'whitefang', 'whitehorse', 'whiterose', 'whitesand', 'whitewater', 'wildcard',
  'wildcat', 'wilderness', 'wildfire', 'wildflower', 'wildthing', 'williamtell', 'windjammer', 'windsor', 'windsurfer', 'winterfell',
  'wintersnow', 'wolverine', 'wonderland', 'woodstock', 'woodpecker', 'worldseries', 'wrangler', 'wrestling', 'wyoming', 'xenomorph',
  'yellowstone', 'yesterday', 'yosemite', 'youngblood', 'yukonriver', 'zeppelin', 'zerohero', 'zeuslightning', 'zigzag', 'zombieland'
];

export const COMMON_PASSWORDS_SET = new Set(
  COMMON_PASSWORDS_RAW.map(p => p.toLowerCase().trim())
);

/**
 * Checks if the provided password appears in the local common passwords list.
 * Case-insensitive comparison.
 */
export function isCommonPassword(password: string): boolean {
  if (!password || typeof password !== 'string') return false;
  return COMMON_PASSWORDS_SET.has(password.toLowerCase().trim());
}
